defaults: &defaults
  host: 127.0.0.1
  port: 27017
  options:
    w: 1
    pool_size: 1
    slave_ok: false
    ssl: false

development:
  <<: *defaults
  database: businessapp_development

test:
  <<: *defaults
  database: businessapp_test
  w: 0

production:
  host: SG-Businessappcluster-6084.servers.mongodirector.com
  port: 27017
  database: businessapp
  user: frank
  password: <%= ENV['MONGO_DB_PASSWORD'] %>
  
  